-- Create Users Table
create table users (
  id bigint generated by default as identity primary key,
  email text not null unique,
  password_hash text not null,
  full_name text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Link credentials to users
alter table credentials add column user_id bigint references users(id);
